[phases.setup]
nixPkgs = ["nodejs_24_x", "pnpm-9_x"]

[phases.install]
cmds = ["cd api && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd api && npx prisma generate"]

[start]
cmd = "cd api && npx prisma migrate deploy && node src/app.js"
