[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm install --ignore-workspace --ignore-scripts"]

[phases.build]
cmds = ["echo 'build skipped'"]

[start]
cmd = "node src/app.js"
